### ISSUE TITLE
BleCommunicationNix

### ISSUE THREAD

**Issue by mauriziodidomenico** [dimamedia/RuuviTag-logger#2]
Hi probably it's my fault, but i can't get running it.
`pi@ruuvi:~/ruuvitag $ sudo ./ruuvitag-logger.py`

`Traceback (most recent call last):
  File "./ruuvitag-logger.py", line 4, in <module> from ruuvitag_sensor.ble_communication import BleCommunicationNix
ImportError: No module named 'ruuvitag_sensor'`

Any advice welcome.

**Comment by rollecode** [comment]
I have the same issue. How did you get it solved? ruuvitag-sensor and dependencies installed. Raspberry Pi 4.

**Comment by mauriziodidomenico** [comment]
Sorry, it's already 3 years ago. i don't have a clue. Not even if i failed or solved!
